// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/jimmmisss/server-api-context/internal/db"
	"github.com/jimmmisss/server-api-context/internal/handler"
)

// Injectors from wire.go:

func Wire(db2 *db.ConnDB) *handler.CotacaoHandler {
	cotacaoRepository := ProviderRepositoryCotacao()
	cotacaoAPI := ProviderApiServiceCotacao()
	cotacaoService := ProviderServiceCotacao(cotacaoRepository, cotacaoAPI)
	cotacaoHandler := ProviderHandlerCotacao(cotacaoService)
	return cotacaoHandler
}
